version: "2.1"
services:
  auth-api-db:
    container_name: auth-api-db
    build: ./auth-api-db
    ports:
      - "27017:27017"
    env_file:
      - ./auth-api-db/.env
  restaurant-api-db:
    container_name: restaurant-api-db
    build: ./restaurant-api-db
    ports:
      - "27018:27017"
    env_file:
      - ./restaurant-api-db/.env
  data-controller-db:
    container_name: data-controller-db
    build: ./data-controller-db
    ports:
      - "27019:27017"
    env_file:
      - ./data-controller-db/.env
  r-zookeeper:
    container_name: r-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  r-kafka:
    container_name: r-kafka
    image: wurstmeister/kafka:2.11-1.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "
        data-controller:1:1,
        data-provider:1:1,"
      KAFKA_ZOOKEEPER_CONNECT: r-zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - r-zookeeper
  restaurant-api:
    container_name: restaurant-api
    build: ./restaurant-api
    depends_on:
      - restaurant-api-db
    env_file:
      - ./restaurant-api/.env
  auth-api:
    container_name: auth-api
    build: ./auth-api
    depends_on:
      - auth-api-db
    env_file:
      - ./auth-api/.env
  data-controller:
    container_name: data-controller
    build: ./data-controller
    depends_on:
      - data-controller-db
    env_file:
      - ./data-controller/.env
  data-provider:
    container_name: data-provider
    build: ./data-provider
    depends_on:
      - restaurant-api-db
    env_file:
      - ./data-provider/.env
